# Generated by Codex on 2026-07-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="保存操作发生时的用户名，避免用户删除后日志失去可读性。",
                        max_length=150,
                        verbose_name="用户名快照",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("admin_login", "管理员登录"),
                            ("country_create", "添加国家数据"),
                            ("country_update", "修改国家数据"),
                            ("country_delete", "删除国家数据"),
                            ("excel_import", "导入 Excel"),
                            ("excel_export", "导出 Excel"),
                        ],
                        max_length=50,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "operation_object",
                    models.CharField(blank=True, max_length=255, verbose_name="操作对象"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="IP 地址"),
                ),
                (
                    "operation_result",
                    models.CharField(
                        choices=[("success", "成功"), ("failed", "失败")],
                        default="success",
                        max_length=20,
                        verbose_name="操作结果",
                    ),
                ),
                ("detail", models.TextField(blank=True, verbose_name="操作详情")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "db_table": "operation_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["username", "operation_type"], name="oplog_user_type_idx"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["created_at"], name="oplog_created_idx"),
        ),
    ]
