// 国家英文名到中文名映射工具

// 常见别名统一映射，便于不同接口字段共用同一套中文显示
const COUNTRY_ALIAS_MAP = {
  USA: "United States",
  "United States of America": "United States",
  UK: "United Kingdom",
  UAE: "United Arab Emirates",
  Korea: "South Korea",
};

// 国家英文名到中文名映射
export const COUNTRY_NAME_MAP = {
  Afghanistan: "阿富汗",
  Albania: "阿尔巴尼亚",
  Algeria: "阿尔及利亚",
  Angola: "安哥拉",
  Argentina: "阿根廷",
  Armenia: "亚美尼亚",
  Australia: "澳大利亚",
  Austria: "奥地利",
  Azerbaijan: "阿塞拜疆",
  Bahamas: "巴哈马",
  Bahrain: "巴林",
  Bangladesh: "孟加拉国",
  Belarus: "白俄罗斯",
  Belgium: "比利时",
  Belize: "伯利兹",
  Benin: "贝宁",
  Bhutan: "不丹",
  Bolivia: "玻利维亚",
  "Bosnia and Herzegovina": "波斯尼亚和黑塞哥维那",
  Botswana: "博茨瓦纳",
  Brazil: "巴西",
  Brunei: "文莱",
  Bulgaria: "保加利亚",
  "Burkina Faso": "布基纳法索",
  Burundi: "布隆迪",
  Cambodia: "柬埔寨",
  Cameroon: "喀麦隆",
  Canada: "加拿大",
  Chad: "乍得",
  Chile: "智利",
  China: "中国",
  Colombia: "哥伦比亚",
  Congo: "刚果",
  "Costa Rica": "哥斯达黎加",
  Croatia: "克罗地亚",
  Cuba: "古巴",
  Cyprus: "塞浦路斯",
  Czechia: "捷克",
  "Czech Republic": "捷克",
  Denmark: "丹麦",
  Djibouti: "吉布提",
  "Dominican Republic": "多米尼加",
  Ecuador: "厄瓜多尔",
  Egypt: "埃及",
  "El Salvador": "萨尔瓦多",
  Estonia: "爱沙尼亚",
  Ethiopia: "埃塞俄比亚",
  Finland: "芬兰",
  France: "法国",
  Gabon: "加蓬",
  Gambia: "冈比亚",
  Georgia: "格鲁吉亚",
  Germany: "德国",
  Ghana: "加纳",
  Greece: "希腊",
  Greenland: "格陵兰",
  Guatemala: "危地马拉",
  Guinea: "几内亚",
  Guyana: "圭亚那",
  Haiti: "海地",
  Honduras: "洪都拉斯",
  "Hong Kong": "中国香港",
  "Hong Kong SAR of China": "中国香港",
  Hungary: "匈牙利",
  Iceland: "冰岛",
  India: "印度",
  Indonesia: "印度尼西亚",
  Iran: "伊朗",
  Iraq: "伊拉克",
  Ireland: "爱尔兰",
  Israel: "以色列",
  Italy: "意大利",
  Jamaica: "牙买加",
  Japan: "日本",
  Jordan: "约旦",
  Kazakhstan: "哈萨克斯坦",
  Kenya: "肯尼亚",
  Kosovo: "科索沃",
  Kuwait: "科威特",
  Kyrgyzstan: "吉尔吉斯斯坦",
  Laos: "老挝",
  "Lao PDR": "老挝",
  Latvia: "拉脱维亚",
  Lebanon: "黎巴嫩",
  Lesotho: "莱索托",
  Liberia: "利比里亚",
  Libya: "利比亚",
  Lithuania: "立陶宛",
  Luxembourg: "卢森堡",
  Macao: "中国澳门",
  Madagascar: "马达加斯加",
  Malawi: "马拉维",
  Malaysia: "马来西亚",
  Mali: "马里",
  Malta: "马耳他",
  Mauritania: "毛里塔尼亚",
  Mauritius: "毛里求斯",
  Mexico: "墨西哥",
  Moldova: "摩尔多瓦",
  "Republic of Moldova": "摩尔多瓦",
  Mongolia: "蒙古",
  Montenegro: "黑山",
  Morocco: "摩洛哥",
  Mozambique: "莫桑比克",
  Myanmar: "缅甸",
  Namibia: "纳米比亚",
  Nepal: "尼泊尔",
  Netherlands: "荷兰",
  "New Zealand": "新西兰",
  Nicaragua: "尼加拉瓜",
  Niger: "尼日尔",
  Nigeria: "尼日利亚",
  "North Korea": "朝鲜",
  "North Macedonia": "北马其顿",
  Norway: "挪威",
  Oman: "阿曼",
  Pakistan: "巴基斯坦",
  Panama: "巴拿马",
  Paraguay: "巴拉圭",
  Peru: "秘鲁",
  Philippines: "菲律宾",
  Poland: "波兰",
  Portugal: "葡萄牙",
  Qatar: "卡塔尔",
  Romania: "罗马尼亚",
  Russia: "俄罗斯",
  "Russian Federation": "俄罗斯",
  Rwanda: "卢旺达",
  "Saudi Arabia": "沙特阿拉伯",
  Senegal: "塞内加尔",
  Serbia: "塞尔维亚",
  "Sierra Leone": "塞拉利昂",
  Singapore: "新加坡",
  Slovakia: "斯洛伐克",
  Slovenia: "斯洛文尼亚",
  Somalia: "索马里",
  "South Africa": "南非",
  "South Korea": "韩国",
  "Republic of Korea": "韩国",
  Spain: "西班牙",
  "Sri Lanka": "斯里兰卡",
  Sudan: "苏丹",
  Suriname: "苏里南",
  Sweden: "瑞典",
  Switzerland: "瑞士",
  Syria: "叙利亚",
  Taiwan: "中国台湾",
  "Taiwan Province of China": "中国台湾",
  Tajikistan: "塔吉克斯坦",
  Tanzania: "坦桑尼亚",
  Thailand: "泰国",
  Togo: "多哥",
  Tunisia: "突尼斯",
  Turkey: "土耳其",
  Türkiye: "土耳其",
  Turkmenistan: "土库曼斯坦",
  Uganda: "乌干达",
  Ukraine: "乌克兰",
  "United Arab Emirates": "阿联酋",
  "United Kingdom": "英国",
  "United States": "美国",
  Uruguay: "乌拉圭",
  Uzbekistan: "乌兹别克斯坦",
  Venezuela: "委内瑞拉",
  Vietnam: "越南",
  "Viet Nam": "越南",
  Yemen: "也门",
  Zambia: "赞比亚",
  Zimbabwe: "津巴布韦",
};

// 判断是否已经是中文或非纯英文文本
export function isLocalizedCountryName(value) {
  return !/^[A-Za-z\s().,'&-]+$/.test(String(value || "").trim());
}

// 统一获取国家中文显示名
export function getLocalizedCountryName(name) {
  if (!name) {
    return "--";
  }

  if (isLocalizedCountryName(name)) {
    return name;
  }

  const normalizedName = COUNTRY_ALIAS_MAP[name] || name;
  return COUNTRY_NAME_MAP[normalizedName] || COUNTRY_NAME_MAP[name] || name;
}
