# Generated by Django 6.0.4 on 2026-04-10 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_zh",
                    models.CharField(
                        help_text="国家的中文名称，例如 日本、法国",
                        max_length=100,
                        unique=True,
                        verbose_name="国家中文名",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="国家的英文名称，例如 Japan、France",
                        max_length=100,
                        unique=True,
                        verbose_name="国家英文名",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="国家简写代码，例如 JP、FR",
                        max_length=10,
                        unique=True,
                        verbose_name="国家代码",
                    ),
                ),
                (
                    "continent",
                    models.CharField(
                        help_text="国家所属大洲，例如 亚洲、欧洲",
                        max_length=50,
                        verbose_name="所属洲",
                    ),
                ),
                (
                    "capital",
                    models.CharField(
                        blank=True,
                        help_text="国家首都名称，可为空",
                        max_length=100,
                        verbose_name="首都",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="国家官方语言，可为空",
                        max_length=100,
                        verbose_name="官方语言",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        help_text="国家主要货币名称，可为空",
                        max_length=50,
                        verbose_name="货币",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="表示该国家数据是否在系统中启用展示",
                        verbose_name="是否启用",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="当前记录的创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="当前记录的最后更新时间",
                        verbose_name="更新时间",
                    ),
                ),
            ],
            options={
                "verbose_name": "国家信息",
                "verbose_name_plural": "国家信息",
                "db_table": "country",
                "ordering": ["name_zh"],
            },
        ),
        migrations.CreateModel(
            name="CountryIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="该条指标数据对应的年份", verbose_name="年份"
                    ),
                ),
                (
                    "safety_index",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="国家整体安全水平评分，建议 0 到 100",
                        max_digits=5,
                        verbose_name="安全指数",
                    ),
                ),
                (
                    "cost_index",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="国家旅游消费水平评分，建议 0 到 100",
                        max_digits=5,
                        verbose_name="消费指数",
                    ),
                ),
                (
                    "climate_index",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="国家气候舒适度评分，建议 0 到 100",
                        max_digits=5,
                        verbose_name="气候指数",
                    ),
                ),
                (
                    "medical_index",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="国家医疗保障水平评分，建议 0 到 100",
                        max_digits=5,
                        verbose_name="医疗指数",
                    ),
                ),
                (
                    "visa_index",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="国家签证便利程度评分，建议 0 到 100",
                        max_digits=5,
                        verbose_name="签证便利指数",
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="根据多个指标计算出的综合推荐分数",
                        max_digits=5,
                        verbose_name="综合评分",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        blank=True,
                        help_text="指标数据来源说明，可为空",
                        max_length=255,
                        verbose_name="数据来源",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="当前记录的创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="当前记录的最后更新时间",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="指标所属的国家",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicators",
                        to="countries.country",
                        verbose_name="所属国家",
                    ),
                ),
            ],
            options={
                "verbose_name": "国家指标",
                "verbose_name_plural": "国家指标",
                "db_table": "country_indicator",
                "ordering": ["-year", "-overall_score"],
                "unique_together": {("country", "year")},
            },
        ),
    ]
