# Generated by Codex on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="countryindicator",
            name="tourism_index",
            field=models.DecimalField(
                decimal_places=2,
                default=50,
                help_text="反映国家旅游资源、接待能力和目的地吸引力的综合评分，建议 0 到 100。",
                max_digits=5,
                verbose_name="旅游适宜指数",
            ),
        ),
    ]
