# Generated by Django 6.0.4 on 2026-04-10 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        help_text="用户在系统中的显示名称",
                        max_length=50,
                        verbose_name="用户昵称",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "男"), ("female", "女"), ("unknown", "未知")],
                        default="unknown",
                        help_text="用户性别信息，默认未知",
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="用户年龄，可为空",
                        null=True,
                        verbose_name="年龄",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="用户联系电话，可为空",
                        max_length=20,
                        verbose_name="手机号",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="用户自我描述信息",
                        verbose_name="个人简介",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="当前记录的创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="当前记录的最后更新时间",
                        verbose_name="更新时间",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="关联 Django 内置用户表中的用户记录",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户扩展信息",
                "verbose_name_plural": "用户扩展信息",
                "db_table": "user_profile",
            },
        ),
    ]
