# Generated by Django 6.0.4 on 2026-04-10 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("countries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_continent",
                    models.CharField(
                        blank=True,
                        help_text="用户更希望前往的大洲，可为空",
                        max_length=50,
                        verbose_name="偏好洲别",
                    ),
                ),
                (
                    "budget_level",
                    models.CharField(
                        choices=[
                            ("low", "低预算"),
                            ("medium", "中等预算"),
                            ("high", "高预算"),
                        ],
                        default="medium",
                        help_text="用户可接受的旅游预算等级",
                        max_length=20,
                        verbose_name="预算等级",
                    ),
                ),
                (
                    "safety_weight",
                    models.PositiveIntegerField(
                        default=40,
                        help_text="用户对安全因素的重视程度，建议 0 到 100",
                        verbose_name="安全权重",
                    ),
                ),
                (
                    "cost_weight",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="用户对消费成本的重视程度，建议 0 到 100",
                        verbose_name="消费权重",
                    ),
                ),
                (
                    "climate_weight",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="用户对气候舒适度的重视程度，建议 0 到 100",
                        verbose_name="气候权重",
                    ),
                ),
                (
                    "medical_weight",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="用户对医疗保障的重视程度，建议 0 到 100",
                        verbose_name="医疗权重",
                    ),
                ),
                (
                    "visa_weight",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="用户对签证便利性的重视程度，建议 0 到 100",
                        verbose_name="签证权重",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        help_text="用户补充说明，例如偏好海岛、避开寒冷地区",
                        max_length=255,
                        verbose_name="偏好备注",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="当前记录的创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="该条偏好记录所属的用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户偏好记录",
                "verbose_name_plural": "用户偏好记录",
                "db_table": "user_preference",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="系统根据偏好和国家指标计算出的推荐得分",
                        max_digits=5,
                        verbose_name="推荐得分",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="推荐该国家的简要原因说明",
                        max_length=255,
                        verbose_name="推荐原因",
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="该国家在当前推荐结果中的排名",
                        verbose_name="推荐排名",
                    ),
                ),
                (
                    "is_viewed",
                    models.BooleanField(
                        default=False,
                        help_text="用户是否查看过该条推荐记录",
                        verbose_name="是否已查看",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="当前记录的创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="系统最终推荐的国家",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_records",
                        to="countries.country",
                        verbose_name="推荐国家",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="该条推荐记录所属的用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
                (
                    "preference",
                    models.ForeignKey(
                        blank=True,
                        help_text="生成该推荐结果时参考的用户偏好记录",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendation_records",
                        to="recommendation.userpreference",
                        verbose_name="关联偏好",
                    ),
                ),
            ],
            options={
                "verbose_name": "推荐结果记录",
                "verbose_name_plural": "推荐结果记录",
                "db_table": "recommendation_record",
                "ordering": ["rank", "-created_at"],
            },
        ),
    ]
